--
-- Generated by pg2mysql
--
set foreign_key_checks = off;
DROP DATABASE IF EXISTS public;
CREATE DATABASE public;
CREATE TABLE public.serial_pk (
    `pk` integer NOT NULL,
    `c1` integer,
    `c2` integer
);

erial_pk_pk_seq'::regclass);
INSERT INTO public.serial_pk VALUES (1, 0, 0);
INSERT INTO public.serial_pk VALUES (2, 1, 1);
ALTER TABLE serial_pk AUTO_INCREMENT = 2;
ALTER TABLE public.serial_pk
ADD CONSTRAINT serial_pk_pkey PRIMARY KEY (`pk`);
ALTER TABLE public.serial_pk MODIFY `pk` integer auto_increment;
