--
-- Generated by pg2mysql
--
set foreign_key_checks = off;
DROP DATABASE IF EXISTS public;
CREATE DATABASE public;
CREATE TABLE public.binary_types (
    `pk` integer NOT NULL,
    `c1` BLOB
);
INSERT INTO public.binary_types VALUES (0, X'6161616161');
